# Generated by Django 4.0.2 on 2022-04-17 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0005_listofmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchparty',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='watchparty',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.watchparty')),
            ],
        ),
    ]
