# Generated by Django 4.0.2 on 2022-04-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedWatchparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_time', models.DateField()),
                ('selected_movie', models.CharField(max_length=200)),
                ('watchparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.watchparty')),
            ],
        ),
    ]
