# Generated by Django 4.0.2 on 2022-04-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_finalizedwatchparty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalizedwatchparty',
            old_name='selected_time',
            new_name='selected_date',
        ),
    ]
