# Generated by Django 4.0.2 on 2022-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_alter_finalizedwatchparty_selected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedwatchparty',
            name='selected_movie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedwatchparty',
            name='selected_time',
            field=models.DateTimeField(null=True),
        ),
    ]
