# Generated by Django 4.0.2 on 2022-04-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_rename_friendgroupmembers_friendgroupmember'),
        ('organizer', '0014_alter_finalizedwatchparty_selected_movie_and_more'),
    ]

    operations = [
    ]
